
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "idFS : DirDir : id '{' Filhos '}'Dir : id '{' '}'Filhos : FilhoFilhos : Filho ',' FilhosFilho : idFilho : Dir"
    
_lr_action_items = {'id':([0,4,11,],[3,5,5,]),'$end':([1,2,7,10,],[0,-1,-3,-2,]),'{':([3,5,],[4,4,]),'}':([4,5,6,7,8,9,10,12,],[7,-6,10,-3,-4,-7,-2,-5,]),',':([5,7,8,9,10,],[-6,-3,11,-7,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'FS':([0,],[1,]),'Dir':([0,4,11,],[2,9,9,]),'Filhos':([4,11,],[6,12,]),'Filho':([4,11,],[8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> FS","S'",1,None,None,None),
  ('FS -> Dir','FS',1,'p_FS','processadorYACC_Diretorias.py',10),
  ('Dir -> id { Filhos }','Dir',4,'p_Dir1','processadorYACC_Diretorias.py',14),
  ('Dir -> id { }','Dir',3,'p_Dir2','processadorYACC_Diretorias.py',20),
  ('Filhos -> Filho','Filhos',1,'p_Filhos1','processadorYACC_Diretorias.py',24),
  ('Filhos -> Filho , Filhos','Filhos',3,'p_Filhos2','processadorYACC_Diretorias.py',28),
  ('Filho -> id','Filho',1,'p_Filho1','processadorYACC_Diretorias.py',32),
  ('Filho -> Dir','Filho',1,'p_Filho2','processadorYACC_Diretorias.py',36),
]
