
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "niLi : '[' E ']'Li : '[' ']'E : N ',' EE : NN : LiN : ni"
    
_lr_action_items = {'[':([0,2,9,],[2,2,2,]),'$end':([1,4,8,],[0,-2,-1,]),']':([2,3,4,5,6,7,8,10,],[4,8,-2,-4,-5,-6,-1,-3,]),'ni':([2,9,],[7,7,]),',':([4,5,6,7,8,],[-2,9,-5,-6,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Li':([0,2,9,],[1,6,6,]),'E':([2,9,],[3,10,]),'N':([2,9,],[5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Li","S'",1,None,None,None),
  ('Li -> [ E ]','Li',3,'p_Li1','gramaticaYACC2.py',9),
  ('Li -> [ ]','Li',2,'p_Li2','gramaticaYACC2.py',14),
  ('E -> N , E','E',3,'p_E1','gramaticaYACC2.py',18),
  ('E -> N','E',1,'p_E2','gramaticaYACC2.py',22),
  ('N -> Li','N',1,'p_N1','gramaticaYACC2.py',26),
  ('N -> ni','N',1,'p_N2','gramaticaYACC2.py',30),
]
