
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ID INTprog : comandoscomandos : comandos : comandos comandocomando : atribcomando : Expatrib : ID '=' ExpExp : Exp '+' ExpExp : Exp '-' ExpExp : INTExp : ID"
    
_lr_action_items = {'ID':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,],[-2,6,-3,-4,-5,-10,-9,12,12,12,-7,-10,-8,-6,]),'INT':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,],[-2,7,-3,-4,-5,-10,-9,7,7,7,-7,-10,-8,-6,]),'$end':([0,1,2,3,4,5,6,7,11,12,13,14,],[-2,0,-1,-3,-4,-5,-10,-9,-7,-10,-8,-6,]),'+':([5,6,7,11,12,13,14,],[8,-10,-9,8,-10,8,8,]),'-':([5,6,7,11,12,13,14,],[9,-10,-9,9,-10,9,9,]),'=':([6,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'prog':([0,],[1,]),'comandos':([0,],[2,]),'comando':([2,],[3,]),'atrib':([2,],[4,]),'Exp':([2,8,9,10,],[5,11,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> prog","S'",1,None,None,None),
  ('prog -> comandos','prog',1,'p_prog','yacc.py',6),
  ('comandos -> <empty>','comandos',0,'p_comandos_varios01','yacc.py',9),
  ('comandos -> comandos comando','comandos',2,'p_comandos_varios02','yacc.py',12),
  ('comando -> atrib','comando',1,'p_comando01','yacc.py',15),
  ('comando -> Exp','comando',1,'p_comando02','yacc.py',18),
  ('atrib -> ID = Exp','atrib',3,'p_atrib','yacc.py',22),
  ('Exp -> Exp + Exp','Exp',3,'p_Exp01','yacc.py',27),
  ('Exp -> Exp - Exp','Exp',3,'p_Exp02','yacc.py',31),
  ('Exp -> INT','Exp',1,'p_Exp03','yacc.py',35),
  ('Exp -> ID','Exp',1,'p_Exp04','yacc.py',39),
]
