
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "niLi : '[' ni ':' ni ']'Li : '[' Es ']'Li : '[' ']'Es : N ',' EsEs : NN : LiN : ni"
    
_lr_action_items = {'[':([0,2,10,],[2,2,2,]),'$end':([1,4,9,14,],[0,-3,-2,-1,]),'ni':([2,8,10,],[3,11,13,]),']':([2,3,4,5,6,7,9,11,12,13,14,],[4,-7,-3,9,-5,-6,-2,14,-4,-7,-1,]),':':([3,],[8,]),',':([3,4,6,7,9,13,14,],[-7,-3,10,-6,-2,-7,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Li':([0,2,10,],[1,7,7,]),'Es':([2,10,],[5,12,]),'N':([2,10,],[6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Li","S'",1,None,None,None),
  ('Li -> [ ni : ni ]','Li',5,'p_Li1','gramaticaYACC2.py',11),
  ('Li -> [ Es ]','Li',3,'p_Li2','gramaticaYACC2.py',15),
  ('Li -> [ ]','Li',2,'p_Li3','gramaticaYACC2.py',20),
  ('Es -> N , Es','Es',3,'p_Es1','gramaticaYACC2.py',27),
  ('Es -> N','Es',1,'p_Es2','gramaticaYACC2.py',32),
  ('N -> Li','N',1,'p_N1','gramaticaYACC2.py',36),
  ('N -> ni','N',1,'p_N2','gramaticaYACC2.py',40),
]
